import Foundation

public struct Quote: Identifiable, Codable, Equatable, Hashable {
    public var id: String { "\(text)-\(author)" }
    public let text: String
    public let author: String

    public init(text: String, author: String) {
        self.text = text
        self.author = author
    }
}

public struct QuoteManager {
    public static let quotes: [Quote] = [
        Quote(text: "The only way to do great work is to love what you do.", author: "Steve Jobs"),
        Quote(text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill"),
        Quote(text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt"),
        Quote(text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius"),
        Quote(text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt"),
        Quote(text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar"),
        Quote(text: "The secret of getting ahead is getting started.", author: "Mark Twain"),
        Quote(text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson"),
        Quote(text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair"),
        Quote(text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis"),
        Quote(text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt"),
        Quote(text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt"),
        Quote(text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein"),
        Quote(text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis"),
        Quote(text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb"),
        Quote(text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe"),
        Quote(text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu"),
        Quote(text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson"),
        Quote(text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney"),
        Quote(text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington"),
        Quote(text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky"),
        Quote(text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford"),
        Quote(text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison"),
        Quote(text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson"),
        Quote(text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau"),
        Quote(text: "When one door of happiness closes, another opens.", author: "Helen Keller"),
        Quote(text: "The mind is everything. What you think you become.", author: "Buddha"),
        Quote(text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein"),
        Quote(text: "The best revenge is massive success.", author: "Frank Sinatra"),
        Quote(text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson"),
        Quote(text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau"),
        Quote(text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller"),
        Quote(text: "If you really look closely, most overnight successes took a long time.", author: "Steve Jobs"),
        Quote(text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson"),
        Quote(text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle"),
        Quote(text: "The only impossible journey is the one you never begin.", author: "Tony Robbins"),
        Quote(text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll"),
        Quote(text: "An unexamined life is not worth living.", author: "Socrates"),
        Quote(text: "Eighty percent of success is showing up.", author: "Woody Allen"),
        Quote(text: "Your limitation—it's only your imagination.", author: "Unknown"),
        Quote(text: "Push yourself, because no one else is going to do it for you.", author: "Unknown"),
        Quote(text: "Great things never come from comfort zones.", author: "Unknown"),
        Quote(text: "Dream it. Wish it. Do it.", author: "Unknown"),
        Quote(text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown"),
        Quote(text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown"),
        Quote(text: "Dream bigger. Do bigger.", author: "Unknown"),
        Quote(text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown"),
        Quote(text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown"),
        Quote(text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery"),
        Quote(text: "Little things make big days.", author: "Unknown"),
        Quote(text: "It's going to be hard, but hard does not mean impossible.", author: "Unknown"),
        Quote(text: "Don't wait for opportunity. Create it.", author: "Unknown"),
        Quote(text: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.", author: "Unknown"),
        Quote(text: "The key to success is to focus on goals, not obstacles.", author: "Unknown"),
        Quote(text: "Dream it. Believe it. Build it.", author: "Unknown"),
        Quote(text: "If it doesn't challenge you, it won't change you.", author: "Fred DeVito"),
        Quote(text: "One day or day one. You decide.", author: "Unknown"),
        Quote(text: "What seems impossible today will one day become your warm-up.", author: "Unknown"),
        Quote(text: "A winner is a dreamer who never gives up.", author: "Nelson Mandela"),
        Quote(text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar"),
        Quote(text: "The pain you feel today will be the strength you feel tomorrow.", author: "Unknown"),
        Quote(text: "Be stronger than your strongest excuse.", author: "Unknown"),
        Quote(text: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupery"),
        Quote(text: "Focus on being productive instead of busy.", author: "Tim Ferriss"),
        Quote(text: "You don't need to see the whole staircase, just take the first step.", author: "Martin Luther King Jr."),
        Quote(text: "Action is the foundational key to all success.", author: "Pablo Picasso"),
        Quote(text: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins"),
        Quote(text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou"),
        Quote(text: "Knowing is not enough; we must apply. Wishing is not enough; we must do.", author: "Johann Wolfgang von Goethe"),
        Quote(text: "We generate fears while we sit. We overcome them by action.", author: "Dr. Henry Link"),
        Quote(text: "Security is mostly a superstition. Life is either a daring adventure or nothing.", author: "Helen Keller"),
        Quote(text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh"),
        Quote(text: "It always seems impossible until it's done.", author: "Nelson Mandela"),
        Quote(text: "There is no substitute for hard work.", author: "Thomas Edison"),
        Quote(text: "The best project you'll ever work on is you.", author: "Sonny Franco"),
        Quote(text: "With the new day comes new strength and new thoughts.", author: "Eleanor Roosevelt"),
        Quote(text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot"),
        Quote(text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt"),
        Quote(text: "Work hard in silence. Let success make the noise.", author: "Frank Ocean"),
        Quote(text: "Don't count the days, make the days count.", author: "Muhammad Ali"),
        Quote(text: "The only thing standing between you and your goal is the story you keep telling yourself.", author: "Jordan Belfort"),
        Quote(text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn"),
        Quote(text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill"),
        Quote(text: "The starting point of all achievement is desire.", author: "Napoleon Hill"),
        Quote(text: "Things work out best for those who make the best of how things work out.", author: "John Wooden"),
        Quote(text: "To live a creative life, we must lose our fear of being wrong.", author: "Joseph Chilton Pearce"),
        Quote(text: "If there is no struggle, there is no progress.", author: "Frederick Douglass"),
        Quote(text: "What you do today can improve all your tomorrows.", author: "Ralph Marston"),
        Quote(text: "Don't let yesterday take up too much of today.", author: "Will Rogers"),
        Quote(text: "We become what we think about most of the time.", author: "Earl Nightingale"),
        Quote(text: "The journey of a lifetime starts with the turning of a page.", author: "Rachel Anders"),
        Quote(text: "Every champion was once a contender that didn't give up.", author: "Gabby Douglas"),
        Quote(text: "Your talent determines what you can do. Your motivation determines how much you're willing to do.", author: "Lou Holtz"),
        Quote(text: "You just can't beat the person who never gives up.", author: "Babe Ruth"),
        Quote(text: "Challenges are what make life interesting. Overcoming them is what makes life meaningful.", author: "Joshua J. Marine"),
        Quote(text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee"),
        Quote(text: "Small daily improvements over time lead to stunning results.", author: "Robin Sharma"),
        Quote(text: "Quality is not an act, it is a habit.", author: "Aristotle"),
        Quote(text: "Progress, not perfection, is what we should be asking of ourselves.", author: "Julia Cameron"),
        Quote(text: "Fall seven times, stand up eight.", author: "Japanese Proverb"),
        Quote(text: "Every accomplishment starts with the decision to try.", author: "John F. Kennedy"),
        Quote(text: "You are what you do, not what you say you'll do.", author: "Carl Jung")
    ]

    public static func randomQuote() -> Quote {
        quotes.randomElement() ?? quotes[0]
    }
}
